### ISSUE TITLE
Eslint test failing

### ISSUE THREAD

**Issue by NeilFraser** [SVG-Edit/svgedit#387]
Running the tests on master fail.  Using a fresh repo synced to master:
```
npm install
npm install eslint-plugin-qunit@latest --save-dev
npm install eslint-plugin-testcafe@latest --save-dev
npm test
```
(The two eslint installs apparently need to be added manually since `npm test` terminates without them.)

The result is:
```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/fraser/Code/svgedit 2/releases/svg-edit-2.8/test/qunit/qunit.js:1064
    at parse (/Users/fraser/Code/svgedit 2/node_modules/eslint-plugin-unicorn/rules/prefer-negative-index.js:244:23)
    at CallExpression (/Users/fraser/Code/svgedit 2/node_modules/eslint-plugin-unicorn/rules/prefer-negative-index.js:267:18)
    at /Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at /Users/fraser/Code/svgedit 2/node_modules/eslint/lib/linter/linter.js:936:32
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! svgedit@5.1.0 eslint: `eslint --ext js,md,html .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the svgedit@5.1.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fraser/.npm/_logs/2020-02-20T18_43_19_668Z-debug.log
ERROR: "eslint" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@5.1.0 prep-no-core-rollup: `run-s eslint build-html build-by-config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svgedit@5.1.0 prep-no-core-rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fraser/.npm/_logs/2020-02-20T18_43_19_698Z-debug.log
ERROR: "prep-no-core-rollup" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@5.1.0 prep: `run-s prep-no-core-rollup rollup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svgedit@5.1.0 prep script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fraser/.npm/_logs/2020-02-20T18_43_19_724Z-debug.log
ERROR: "prep" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@5.1.0 test-no-cov: `run-s prep test-only`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svgedit@5.1.0 test-no-cov script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fraser/.npm/_logs/2020-02-20T18_43_19_750Z-debug.log
ERROR: "test-no-cov" exited with 1.
npm ERR! Test failed.  See above for more details.
```

The contents of `/Users/fraser/.npm/_logs/2020-02-20T18_43_19_668Z-debug.log` is:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.2.0/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eslint'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v13.2.0
4 verbose run-script [ 'preeslint', 'eslint', 'posteslint' ]
5 info lifecycle svgedit@5.1.0~preeslint: svgedit@5.1.0
6 info lifecycle svgedit@5.1.0~eslint: svgedit@5.1.0
7 verbose lifecycle svgedit@5.1.0~eslint: unsafe-perm in lifecycle true
8 verbose lifecycle svgedit@5.1.0~eslint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fraser/Code/svgedit 2/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fraser/Code/svgedit 2/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fraser/Code/svgedit 2/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fraser/Code/svgedit 2/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fraser/Code/svgedit 2/node_modules/.bin:/Users/fraser/Applications/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/fraser/Applications/apache-ant-1.9.4/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle svgedit@5.1.0~eslint: CWD: /Users/fraser/Code/svgedit 2
10 silly lifecycle svgedit@5.1.0~eslint: Args: [ '-c', 'eslint --ext js,md,html .' ]
11 silly lifecycle svgedit@5.1.0~eslint: Returned: code: 2  signal: null
12 info lifecycle svgedit@5.1.0~eslint: Failed to exec eslint script
13 verbose stack Error: svgedit@5.1.0 eslint: `eslint --ext js,md,html .`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1023:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
14 verbose pkgid svgedit@5.1.0
15 verbose cwd /Users/fraser/Code/svgedit 2
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "eslint"
18 verbose node v13.2.0
19 verbose npm  v6.13.1
20 error code ELIFECYCLE
21 error errno 2
22 error svgedit@5.1.0 eslint: `eslint --ext js,md,html .`
22 error Exit status 2
23 error Failed at the svgedit@5.1.0 eslint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

I asked my colleague @cpcallen to replicate this issue, and he ran into problems even earlier.  So his issues are being filed separately.

**Comment by brettz9** [comment]
Apologies, due to a very slow connection, I had not been able to work against a clone with the submodules that have recently been added so as to have noticed this problem.

(Note that these submodules are only necessary for getting at the old releases, and were added in this manner so Github Pages could host them along with `master` without need for modifications.)

Our eslint ignore file had not been ignoring those old releases and so the eslint script which was run as part of the test script was therefore discovering eslint configs within the old releases which relied on plugins which are no longer present or needed, thus giving errors.

This should now be fixed.
